apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: onboardingredhat1workflow
  description: A workflow for onboarding applications to OCP cluster
  annotations:
    argocd/app-selector: rht-gitops.com/janus-argocd=onboardingredhat1workflow
    backstage.io/kubernetes-namespace: orchestrator-gitops
    backstage.io/kubernetes-id: onboardingredhat1workflow-ci
    janus-idp.io/tekton: onboardingredhat1workflow
    github.com/project-slug: redhat-1/onboarding-redhat-1
    gitlab.com/project-slug: redhat-1/onboarding-redhat-1
spec:
  type: workflow-project
  system: system:default/janus-orchestrator
  lifecycle: development
  owner: user:guest
